feat!: adding format (mime type) as required column field of record
MapColonies/raster-catalog-manager pull request #49
Opened 2023-10-02 08:29 UTC by ronenkapelian

Format column - mime type representation

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✔                                                                        |
| Deprecations    | ✔                                                                       |
| Documentation   | ✖                                                                        |
| Tests added     | ✔                                                                        |
| Chore            | ✖                                                                       |

* Added new column called format
* format is string posiible values (image/png | image/jpeg)
* required field - not null

2023-10-02 11:31 UTC, CL-SHLOMIKONCHA approved these changes

2023-10-08 13:32 UTC, asafMasa requested changes
Please mind my comment

2024-02-18 09:56 UTC, asafMasa approved these changes

2024-02-18 09:58 UTC, closed without merging

2024-02-18 09:59 UTC, ronenkapelian commented
deprecated