Helm chart refactor
MapColonies/raster-catalog-manager pull request #52
Opened 2024-01-02 14:02 UTC by CL-SHLOMIKONCHA

2024-01-16 11:27 UTC, asafMasa requested changes

2024-01-17 09:06 UTC, CL-SHLOMIKONCHA commented on helm/templates/_resources.tpl
> +{{- end }}
fixed

2024-01-17 09:06 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +      cert: certs/cert.pem
fixed

2024-01-17 09:09 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +    userName: postgres
this local values are only for secret create , i would remove it at all but i didn't touch it right now its less important

2024-01-17 09:42 UTC, asafMasa approved these changes

2024-01-17 11:34 UTC, merged