build: upgrade node and packages
MapColonies/raster-catalog-manager pull request #53
Opened 2024-02-05 14:19 UTC by RonitKissis

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✔/✖                                                                       |

2024-02-05 14:46 UTC, asafMasa requested changes
please try to upgrade thos version also

2024-02-05 14:46 UTC, asafMasa commented on package.json
>      "@map-colonies/error-types": "^1.1.0",
[v1.1.5](https://github.com/MapColonies/error-types/releases/tag/v1.1.5)

2024-02-05 14:46 UTC, asafMasa commented on package.json
>      "@map-colonies/error-express-handler": "^2.1.0",
[v2.1.0](https://github.com/MapColonies/error-express-handler/releases/tag/v2.1.0)

2024-02-05 14:46 UTC, asafMasa commented on package.json
>      "@map-colonies/mc-model-types": "^14.1.2",
15.2.0

2024-02-06 08:11 UTC, RonitKissis commented on package.json
>      "@map-colonies/mc-model-types": "^14.1.2",
cant upgrade, there are breaking changes.

2024-02-06 08:31 UTC, asafMasa approved these changes

2024-02-06 08:32 UTC, merged