feat!: update to new db schema (MAPCO-4232, MAPCO-4290 )
MapColonies/raster-catalog-manager pull request #63
Opened 2024-05-20 08:53 UTC by RonitKissis

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✔                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✔                                                                        |
| Chore            | ✖                                                                       |

2024-05-22 07:16 UTC, asafMasa requested changes

2024-05-26 07:33 UTC, RonitKissis commented on src/DAL/migration/fullSchema.sql
> +    (imaging_time_end_utc ASC NULLS LAST);
added index to min_resolution_meter ( max_resolution_meter has one) - the other fields didnt have indexes

2024-05-26 12:11 UTC, asafMasa approved these changes

2024-05-28 14:47 UTC, asafMasa requested changes

2024-07-01 15:42 UTC, asafMasa requested changes

2024-07-01 15:42 UTC, asafMasa commented on .github/workflows/build_and_push.yaml
> +      uses: MapColonies/shared-workflows/.github/workflows/build-and-push-docker.yaml@v1
v1 or master?

2024-07-01 15:42 UTC, asafMasa commented on .github/workflows/build_and_push.yaml
> +      uses: MapColonies/shared-workflows/.github/workflows/build-and-push-helm.yaml@v1
v1 or master?

2024-07-01 15:42 UTC, asafMasa commented on .github/workflows/release-on-tag-push.yaml
> +    uses: MapColonies/shared-workflows/.github/workflows/release-on-tag-push.yaml@v1
v1 or master?

2024-07-01 15:42 UTC, asafMasa commented on .github/workflows/release-on-tag-push.yaml
> +    secrets: inherit
end of file * 3 workflows

2024-07-01 15:42 UTC, asafMasa commented on package.json
> +}
EOF

2024-07-02 06:54 UTC, RonitKissis commented on .github/workflows/release-on-tag-push.yaml
> +    secrets: inherit
done

2024-07-02 06:55 UTC, RonitKissis commented on package.json
> +}
done

2024-08-22 14:01 UTC, asafMasa approved these changes

2024-11-07 07:23 UTC, merged